
# Generated by Django 3.2.24 on 2024-02-21 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('description', models.TextField(blank=1, null=1, verbose_name='Description')),
                ('description_as_markdown', models.BooleanField(default=False, verbose_name='As markdown')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cost')),
                ('cover', models.CharField(default='no_image.svg', max_length=25, verbose_name='Cover')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title_verbose')),
                ('preambule', models.CharField(max_length=1024, verbose_name='Preambule_verbose')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Body_verbose')),
                ('body_as_markdown', models.BooleanField(default=False, verbose_name='As markdown verbose')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created verbose')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update_verbose')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(verbose_name='Lesson_number')),
                ('title', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_as_markdown', models.BooleanField(default=False, verbose_name='As markdown')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('deleted', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.courses')),
            ],
            options={
                'ordering': ('course', 'num'),
            },
        ),
        migrations.CreateModel(
            name='CourseTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_teacher', models.CharField(max_length=128, verbose_name='Name teacher')),
                ('surname_teacher', models.CharField(max_length=128, verbose_name='Surname teacher')),
                ('day_birth', models.DateTimeField(verbose_name='BD')),
                ('deleted', models.BooleanField(default=False)),
                ('course', models.ManyToManyField(to='mainapp.Courses')),
            ],
        ),
    ]
