# Generated by Django 3.2.24 on 2024-03-10 13:12

from django.db import migrations






class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
    ]
