# Generated by Django 3.2.24 on 2024-03-17 12:25

from django.db import migrations

def forwards_func(apps, schema_editor):
    Courses = apps.get_model('mainapp', 'Courses')
    # Create models objects
    Courses.objects.create(
        id = 9,
        name='iOS разработчик',
        description='В этом курсе вы изучите основы языка Swift, Objective-C, а также научитесь '
                    'работать с фреймворком SwiftUI',
        description_as_markdown=True,
        cost=10000.55,
        cover='img/swift.jpg',
    )

def reverse_func(apps, schema_editor):
    # Get model
    Courses = apps.get_model('mainapp', 'Courses')
    # Delete objects
    Courses.objects.filter(id=9).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_migration_for_courses'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
