# Generated by Django 3.2.24 on 2024-03-17 18:05

from django.db import migrations

def forward_func(apps, schema_editor):
    ...


def reverse_func(apps, schema_editor):
    ...

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_migration_id_9'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func)
        ]
