# Generated by Django 3.2.24 on 2024-03-26 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_migration_for_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intermediate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('course_inter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.courses')),
                ('teacher_inter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.courseteachers')),
            ],
        ),
    ]
