# Generated by Django 3.2.24 on 2024-03-26 23:01

from django.db import migrations

from faker import Faker
from random import randint as rINT
def forwards_func(apps, schema_editor):
    Teacher = apps.get_model('mainapp', 'CourseTeachers')
    Course = apps.get_model('mainapp', 'Courses')
    Inter = apps.get_model('mainapp', 'Intermediate')
    faker_ = Faker('ru-RU')

    for i in range(6, 8):
        db = faker_.date_of_birth()
        teacher = Teacher.objects.create(
            id = i,
            name_teacher = faker_.first_name_female(),
            surname_teacher = faker_.last_name_female(),
            day_birth=f'{db.year}-{db.month}-{db.day}'
        )
        teacher_inter_course = Inter(
            teacher_inter = teacher,
            course_inter = Course.objects.get(id=rINT(1, 9))
        )
        teacher_inter_course.save()

def reverse_func(apps, schema_editor):
    Teacher = apps.get_model('mainapp', 'CourseTeachers')
    Teacher.objects.filter(id=len(Teacher.objects.all())).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_intermediate'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
