# Generated by Django 3.2.24 on 2024-03-28 21:17

from django.db import migrations

def forwards_func(apps, schema_editor):
    News = apps.get_model('mainapp','News')
    News.objects.all().delete()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_transfers_news'),
    ]

    operations = [
        migrations.RunPython(
            forwards_func,
            reverse_func
        )
    ]
