# Generated by Django 3.2.24 on 2024-03-28 21:28

from django.db import migrations

def forwards_func(apps, schema_editor):
    DataTransfer = apps.get_model('mainapp', 'DataTransfer')
    News = apps.get_model('mainapp','News')
    for i in range(1, len(DataTransfer.objects.all()) + 1):
        News.objects.create(
        id = i,
        title= DataTransfer.objects.get(id=i).title_transfer,
        preambule = DataTransfer.objects.get(id=i).preambule_transfer,
        body = DataTransfer.objects.get(id=i).body_transfer,
        body_as_markdown = DataTransfer.objects.get(id=i).body_as_markdown_transfer,
        created = DataTransfer.objects.get(id=i).created_transfer,
        updated = DataTransfer.objects.get(id=i).updated_transfer,
        deleted = DataTransfer.objects.get(id=i).deleted_transfer
        )

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_del_news'),
    ]

    operations = [
        migrations.RunPython(
            forwards_func,
            reverse_func
        )
    ]
