# Generated by Django 3.2.24 on 2024-03-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_transfer_back'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataTransfer',
        ),
    ]
