# Generated by Django 3.2.24 on 2024-04-07 22:14

from django.db import migrations

def forwards_func(apps, schema_editor):
    Courses = apps.get_model('mainapp', 'Courses')
    for i in range(1, len(Courses.objects.all()) + 1):
        course_python = Courses.objects.get(id=i)
        course_python.description_as_markdown = False
        course_python.save()
    # for i in range(1, len(courses.objects.all()) + 1):
    #     courses.objects.get(id=i).description_as_markdown = False
    #     courses.objects.get(id=i).save()

def reverse_func(apps, schema_editor):
    ...

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_change_description_courses'),
    ]

    operations = [
        migrations.RunPython(
            forwards_func,
            reverse_func
        )
    ]
