# Generated by Django 3.2.24 on 2024-04-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_false_markdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_transfer', models.CharField(max_length=256, verbose_name='Title_verbose')),
                ('preambule_transfer', models.CharField(max_length=1024, verbose_name='Preambule_verbose')),
                ('body_transfer', models.TextField(blank=True, null=True, verbose_name='Body_verbose')),
                ('body_as_markdown_transfer', models.BooleanField(default=False, verbose_name='As markdown verbose')),
                ('created_transfer', models.DateTimeField(auto_now_add=True, verbose_name='Created verbose')),
                ('updated_transfer', models.DateTimeField(auto_now=True, verbose_name='Update_verbose')),
                ('deleted_transfer', models.BooleanField(default=False)),
            ],
        ),
    ]
