# Generated by Django 3.2.24 on 2024-05-21 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_datatransfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created',), 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
