# Generated by Django 5.0.6 on 2024-06-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['pk'], 'verbose_name': 'Courses', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='courseteachers',
            options={'ordering': ['pk'], 'verbose_name': 'CourseTeachers', 'verbose_name_plural': 'CourseTeachers'},
        ),
    ]
