# Generated by Django 5.0.6 on 2024-06-17 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_courses_options_alter_courseteachers_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body_as_markdown',
            field=models.BooleanField(default=False, verbose_name='Разметка markdown'),
        ),
        migrations.AlterField(
            model_name='news',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удаленная новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preambule',
            field=models.CharField(max_length=1024, verbose_name='Описание новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Заголовок новости'),
        ),
        migrations.CreateModel(
            name='CourseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(default='No feedback', verbose_name='Feedback')),
                ('rating', models.SmallIntegerField(choices=[(5, '*****'), (4, '****'), (3, '***'), (2, '**'), (1, '*')], default=5, verbose_name='Rating')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('deleted', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.courses', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
