# Generated by Django 3.2.24 on 2024-05-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_datatransfer'),
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='purchased_courses',
            field=models.ManyToManyField(to='mainapp.Courses'),
        ),
    ]
