# Generated by Django 5.0.6 on 2024-11-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_customuser_age_alter_customuser_avatar_and_more'),
        ('mainapp', '0023_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='purchased_courses',
            field=models.ManyToManyField(null=True, to='mainapp.courses'),
        ),
    ]
