# Generated by Django 5.0.6 on 2024-11-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_customuser_purchased_courses'),
        ('mainapp', '0023_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='purchased_courses',
            field=models.ManyToManyField(blank=True, to='mainapp.courses'),
        ),
    ]
